const url = import.meta.env.BASE_URL;

export const dummy = [
  {
    id: `1`,
    title: `LAS PALMERAS CONDOMINIO CLUB`,
    subtitle: `Oasis residencial cerca al mar`,
    text: `Vivir alejado del movimiento diario de las ciudades siempre ha sido el motor de innumerables proyectos inmobiliarios alrededor del mundo. En nuestro contexto, esos escenarios se han situado mayormente en las zonas campestres al este de Trujillo; sin embargo, poco a poco los balnearios se muestran como opciones más atractivas para residir de forma permanente.De esta manera, Las Palmeras Condominio Club es un proyecto que desarrollamos con especial dedicación porque representa un giro importante en la oferta actual. Ubicado a las puertas de Huanchaco, busca no solo crear un mundo propio para sus habitantes, sino relacionarse directamente con el contexto a través de una zona comercial abierta a la comunidad. Hacia el interior, la trama se organiza a partir de un amplio club house en el que todos pueden desarrollar diversas actividades de índole recreativa y social. Esto se complementa de forma general con las áreas verdes destinadas a la recreación, que se ubican de modo tal que las familias siempre cuenten con un parque cerca para relacionarse tanto visual como espacialmente.Finalmente, conscientes del lenguaje que queremos darle a un conjunto de este tipo y esta magnitud, propusimos unidades de vivienda con una expresión fresca y de geometría simple, pero sin perder el toque acogedor, una característica que también se traslada a la función en el interior de cada una, asegurando el confort del usuario desde el camino de ingreso hasta el espacio más íntimo.`,
    images: [
      `${url}/tmp/las-palmeras-condominio-club-1.jpg`,
      `${url}/tmp/las-palmeras-condominio-club-2.jpg`,
      `${url}/tmp/las-palmeras-condominio-club-3.jpg`,
      `${url}/tmp/las-palmeras-condominio-club-5.jpg`,
      `${url}/tmp/las-palmeras-condominio-club-6.jpg`,
      `${url}/tmp/las-palmeras-condominio-club-7.jpg`,
      `${url}/tmp/las-palmeras-condominio-club-8.jpg`,
      `${url}/tmp/las-palmeras-condominio-club-9.jpg`,
      `${url}/tmp/las-palmeras-condominio-club-10.jpg`,
      `${url}/tmp/las-palmeras-condominio-club-11.jpg`,
      `${url}/tmp/las-palmeras-condominio-club-12.jpg`,
      `${url}/tmp/las-palmeras-condominio-club-13.jpg`,
      `${url}/tmp/las-palmeras-condominio-club-14.jpg`,
      `${url}/tmp/las-palmeras-condominio-club-15.jpg`,
    ],
    url: `${url}/proyectos/las-palmeras-condomio-club`,
    year: 2020,
    featuredImage: `${url}/tmp/las-palmeras-condominio-club-1.jpg`,
    coverImage: `${url}/tmp/portada-las-palmeras-condominio-club.jpg`,
    category: `Arquitectura`,
  },
  {
    id: `2`,
    title: `INTERIOR JAY LOUNGE`,
    subtitle: `Sofisticación frente al mar`,
    text: `Este proyecto se desarrolla en un departamento de quinto piso en el Malecón de la Reserva, Miraflores. Su ubicación en uno de los distritos más cosmopolitas de la capital, su relación visual directa con el mar y el estilo de vida de nuestros clientes confluyeron para dar como resultado una propuesta de líneas sencillas y matices cambiantes que van desde los colores claros y fríos como la neblina matutina, materiales cálidos como el sol de la tarde hasta acabados oscuros y elegantes como la noche. Toda la atmósfera conseguida en esta intervención se encuentra contenida en el elemento protagonista de la sala: la butaca Jay Lounge. Creada en 2017 por el diseñador francés Jean-Marie Massaud, esta pieza icónica del diseño contemporáneo es una reinterpretación de los clásicos bergères (poltronas o butacas de brazos acolchados), presentando un volumen ligero, de líneas más libres, orgánicas y estilizadas, pero sin descuidar en ningún momento la comodidad del usuario. Así, la inclusión de este elemento de alto valor artístico y funcional a nuestro diseño no solo aporta a la estética del conjunto, sino también a la calidad de vida de sus ocupantes.`,
    images: [
      `${url}/tmp/interior-jay-lounge-1.jpg`,
      `${url}/tmp/interior-jay-lounge-2.jpg`,
      `${url}/tmp/interior-jay-lounge-3.jpg`,
      `${url}/tmp/interior-jay-lounge-4.jpg`,
      `${url}/tmp/interior-jay-lounge-5.jpg`,
    ],
    url: `${url}/proyectos/interior-jay-lounge`,
    year: 2020,
    featuredImage: `${url}/tmp/interior-jay-lounge-4.jpg`,
    coverImage: `${url}/tmp/portada-interior-jay-lounge.jpg`,
    category: `Interiorismo`,
  },
  {
    id: `3`,
    title: `SB 10`,
    subtitle: `Linealidad acogedora`,
    text: `La construcción de los proyectos, en general, es un recorrido que nos lleva a concretar espacial y materialmente el concepto que buscamos desde los primeros trazos en papel, que en el caso de esta casa de campo se resumían en linealidad, transparencia y calidez. En este diseño planteamos una volumetría totalmente horizontal como remate de un amplio jardín de bienvenida y, a través de ella, una apertura visual total hacia el frente –con la terraza, bar y piscina– y, de manera más privada, hacia el fondo. Todo esto se logró con mamparas corridas en ambas fachadas, que exteriorizan la calidez del interior con la carpintería de madera, además de las celosías y pérgolas.`,
    images: [
      `${url}/tmp/casa-de-campo-sb10-1.jpg`,
      `${url}/tmp/casa-de-campo-sb10-2.jpg`,
      `${url}/tmp/casa-de-campo-sb10-3.jpg`,
      `${url}/tmp/casa-de-campo-sb10-5.jpg`,
      `${url}/tmp/casa-de-campo-sb10-6.jpg`,
      `${url}/tmp/casa-de-campo-sb10-7.jpg`,
      `${url}/tmp/casa-de-campo-sb10-8.jpg`,
    ],
    url: `${url}/proyectos/casa-de-campo-sb-10`,
    year: 2020,
    featuredImage: `${url}/tmp/casa-de-campo-sb10-1.jpg`,
    coverImage: `${url}/tmp/portada-casa-de-campo-sb10.jpg`,
    category: `Construcción`,
  },
  {
    id: `4`,
    title: `VALLE HOTEL`,
    subtitle: `Confort en la ciudad`,
    text: `El crecimiento de la ciudad de Trujillo no solo se refleja en nuevas zonas urbanas, si no en la nueva oferta de establecimientos comerciales y de hospedaje a disposición del público local y visitante. Nuestro diseño aprovecha su ubicación en un lote con frente a una avenida principal, una calle secundaria y un parque residencial para explotar las visuales panorámicas que rodean el proyecto y se van extendiendo al usuario a medida que sube de nivel. Los materiales se han escogido de una paleta sobria y cálida para exteriorizar la serenidad que se transmite a los huéspedes en los espacios desarrollados en el interior.`,
    images: [
      `${url}/tmp/valle-hotel-1.jpg`,
      `${url}/tmp/valle-hotel-2.jpg`,
      `${url}/tmp/valle-hotel-3.jpg`,
    ],
    url: `${url}/proyectos/valle-hotel`,
    year: 2020,
    featuredImage: `${url}/tmp/valle-hotel-1.jpg`,
    coverImage: `${url}/tmp/portada-valle-hotel.jpg`,
    category: `Arquitectura`,
  },
  {
    id: `5`,
    title: `BAÑO MASTER SUITE    `,
    subtitle: `Espontaneidad elegante    `,
    text: `La vivienda es un sistema donde la función y la forma se complementan para crear un ambiente en el que los usuarios se sientan cómodos, seguros y puedan ser ellos mismos en la espontaneidad del día a día. Por eso, un espacio tan cotidiano como el servicio higiénico del dormitorio principal ha sido intervenido por nosotros para lograr ese objetivo. Llevando el diseño hasta el más íntimo de los espacios, aportamos calidez y elegancia con una paleta de colores tierra, madera y enchapes de piedra, que, junto a la iluminación, terminan de englobar esta atmósfera.`,
    images: [
      `${url}/tmp/master-suite-1.jpg`,
      `${url}/tmp/master-suite-2.jpg`,
      `${url}/tmp/master-suite-4.jpg`,
    ],
    url: `${url}/proyectos/bano-master-suite`,
    year: 2020,
    featuredImage: `${url}/tmp/master-suite-1.jpg`,
    coverImage: `${url}/tmp/portada-master-suite.jpg`,
    category: `Interiorismo`,
  },
  {
    id: `6`,
    title: `FINA ESTAMPA   `,
    subtitle: `El escenario desde el interior `,
    text: `Tal como presentamos la arquitectura de este proyecto en una publicación anterior, aquí se da la búsqueda de un lenguaje sofisticado que esté ligado al nivel de la cocina de este restaurante. Es así que los interiores que desarrollamos responden a esa intención. Los dos primeros niveles dan la bienvenida al usuario con ambientes de paleta sobria de tonos neutros y toques más elegantes, acompañando la experiencia del buen comer con una exhibición de vinos y macerados, sumados a los apliques de madera e iluminación cálida. El tercer nivel, la terraza lounge, se presenta como un ambiente fluido de mayor libertad de detalle y apertura hacia el exterior, con notas más casuales donde destaca el enchape en mosaico color verde, que, junto a la vegetación, le terminan de imprimir ese concepto de aire libre que bien acompaña un after-office o una celebración con amigos.`,
    images: [
      `${url}/tmp/fina-estampa-1-1.jpg`,
      `${url}/tmp/fina-estampa-2-2.jpg`,
      `${url}/tmp/fina-estampa-3-1.jpg`,
      `${url}/tmp/fina-estampa-4.jpg`,
      `${url}/tmp/fina-estampa-5.jpg`,
    ],
    url: `${url}/proyectos/fina-estampa`,
    year: 2020,
    featuredImage: `${url}/tmp/fina-estampa-1-1.jpg`,
    coverImage: `${url}/tmp/portada-fina-estampa.jpg`,
    category: `Interiorismo`,
  },
];
export default dummy;
